[meta]
name = "Dashboard"
author = "Miss"
category = "Overlay"
version = "1.9.7"

blocks = [ "Plugin_Dashboard" ]

[script]
dependencies = [ "VehicleState" ]
timeout = 0
exports = ["Source/Exports.as"]
